### ISSUE TITLE
adding a hollow cylinder as a body?

### ISSUE THREAD

**Issue by remoe** [lo-th/Oimo.js#12]
Hi

I have a bowl as a 3D model and try to add a hollow cylinder as a collision wall on the side. Is this possible? I don't want to add multiple boxes on the side of the bowl. Here are the sample:

![image](https://cloud.githubusercontent.com/assets/804941/3743481/ab0c5fa4-1779-11e4-87e9-e1e83ef20f20.png)

**Comment by lo-th** [comment]
yes is possible with the rev version
just add static cylinder

**Comment by remoe** [comment]
thanks, but sorry, I don't get it to work when the other objects are IN the cylinder. They throw out.

**Comment by lo-th** [comment]
how yes, cylinder only work outside not in the cylinder.
you have to use fixe box , you can use many box if fixed.
is easy to make simple script  for that.

**Comment by remoe** [comment]
Ok, thanks.

**Comment by remoe** [comment]
Here is a quick and dirty sample to create some boxes around a circle:

``` javascript
           var r=10.7;
           var box_angle = 20.0;
           var l = Math.abs(r * Math.cos(box_angle)) ;

           for(var a = 0.0; a < 360; a+=box_angle) {
               var a_ = a * (Math.PI/180);
               var x = r * Math.cos(a_);
               var y = r * Math.sin(a_);
               physics.add_static_box(l,2.0,100,[x,y,0],[0,0,a+90]);
           }
```
