### ISSUE TITLE
Find out when one body hit another?

### ISSUE THREAD

**Issue by remoe** [lo-th/Oimo.js#14]
Hi

I want to do something when one body hit another specific body. Is there any interface to do this?

Thanks

**Comment by Canta** [comment]
There are collision detection classes in Oimo. But no events pattern implemented yet.

I was asking for an event pattern in #11 , with collision detection events in mind. Maybe this give you some ideas of how to do it yourself quick and dirty: https://github.com/lo-th/Oimo.js/issues/11#issuecomment-43652169

**Comment by remoe** [comment]
Thanks for your hint.
