### ISSUE TITLE
Step forward?

### ISSUE THREAD

**Issue by lz000** [lo-th/Oimo.js#18]
Hi @lo-th, is there a way to step forward?
 I tried: 
    delay // milliseconds
    var frames = Math.round(delay / 1000 \* fps);
    for(var i=0; i<frames; i++){
        world.step();
    }
    updatePosition();

but doesn't seem to work. Any suggestion?
Thank you!

**Comment by lo-th** [comment]
hum due to the stucture of Oimo is not possible 
for the moment. the only way is to play simulation 
save all positions and rotations on each frame in array
and reorganize result array.

**Comment by lz000** [comment]
Thank you for your reply! I will see if I can find another way to do this
