### ISSUE TITLE
gravity

### ISSUE THREAD

**Issue by jaredmcqueen** [lo-th/Oimo.js#20]
I'm playing around with some demos and see that there is a world gravity.  I'm working on a project where different objects in the scene each require their own gravity - to either pull or push neighboring objects.

Is there a way to attract / repel rigid bodies based on gravity or will I have to calculate those forces outside of oimo?

**Comment by lo-th** [comment]
yes sure you can remove gravity (0,0,0)
and apply force RigidBody.applyImpulse(position, force);

http://activetheory.net/lab/attraction

**Comment by jaredmcqueen** [comment]
excellent, thanks for your help!

**Comment by x1911** [comment]
@lo-th good, that's what i looking for,  about the applyImpulse function, can you give us a example?

something like a player jump :  player.applyImpulse({x:1, y:0, z:0}, 20);
