### ISSUE TITLE
Error with world.step() function

### ISSUE THREAD

**Issue by QuaziKb** [lo-th/Oimo.js#23]
Hi! I found a bug with the step() function in the oimo.world prototype.

Bodies which are asleep will not wake up if only their angular velocity has changed, because of what looks like a copying error near the top of the function. the offending chunk looks like this, and is easily fixed.

```
      if(tmpB.sleeping){
            var lv=tmpB.linearVelocity;
            var av=tmpB.linearVelocity; <------------------ this should be tmpB.angularVelocity
            var p=tmpB.position;
            var sp=tmpB.sleepPosition;
            var o=tmpB.orientation;
            var so=tmpB.sleepOrientation;
            if(
            lv.x!=0||lv.y!=0||lv.z!=0||
            av.x!=0||av.y!=0||av.z!=0||
            p.x!=sp.x||p.y!=sp.y||p.z!=sp.z||
            o.s!=so.s||o.x!=so.x||o.y!=so.y||o.z!=so.z
            ){
            tmpB.awake();
            continue;
            }
```

I have little experience with GitHub and pull-requests, but I aim to help build on this project, since it seems there are few if any contributors. If someone could help me get started with how to properly fork, get pull requests merged, etc. that'd be great! For starters i'm not sure if i'm supposed to fork the master or gh-pages branch, or if this even matters! I'm a noob with SVN stuff but I have a lot of experience with game engines and rigid body physics (i'm a mechanical engineering student, and have been programming for over a decade). I plan to possibly include support for more body shapes and possibly arbitrary meshes, as well as fix bugs and improve the overall quality of this physics engine, but i'd rather have my additions / fixes merged to the main project than keep them to myself so others could benefit. There really aren't any good js physics engines out there atm which aren't emscripten ports, and i feel i'd be helping a lot of people out by commiting things like this.

**Comment by lo-th** [comment]
Hello QuaziKb your right, i have to change that.
in oimo dev to if( body.linearVelocity.testZero() || body.angularVelocity.testZero() ...

sure you can help me to add more body support. Github is realy good for that.
