### ISSUE TITLE
Friction isn't properly handled?

### ISSUE THREAD

**Issue by QuaziKb** [lo-th/Oimo.js#25]
The coefficients of friction on objects don't seem to be affecting very much. Ideally a coefficient of zero would mean objects could slide freely over one another (like on ice), but it seems there is still a very considerable damping/frictional effect going on which prevents that kind of sliding behavior. Any ideas how i can go about fixing this?

EDIT: actually i found the problem, setting the coefficient of friction/restitution/etc to 0 means the checks when you create a new OIMO.Body() are seeing it as a falsey value and replacing it with the default of 0.4 in the case of friction.

should be replaced with (obj.config[1] === undefined ? 0.4 : obj.config[1]) etc. so 0 is a legal input, but the method of setting a default if a parameter is left out is preserved

**Comment by lo-th** [comment]
yes in javascript a value with 0 mean null and remplace with default 
i have to take care about that 

you can use 0.001 for friction

**Comment by lo-th** [comment]
updated in dev
