### ISSUE TITLE
how to change ```move``` in a body

### ISSUE THREAD

**Issue by jeromeetienne** [lo-th/Oimo.js#26]
I created a body with `{ move: false }` as parameter (so it isnt move by the physics)

later i would like to change this and start to make it move. how can i change that ?

**Comment by jeromeetienne** [comment]
similarly, how can i change the mass of an object ?

**Comment by lo-th** [comment]
hello you can't change move on simulation
move:true for dynamique and false for statique 
but you can force position of dynamique object by body.setPosition(v);

mass is auto you can change density in obj.config[0]
is fixed at start i have to look if is possible to change in time.

look src/dev/util/Body.js
for full possibility

**Comment by jeromeetienne** [comment]
thanks for your prompt answer and those informations :)

in my case, i want to change a dynamic object to static object, should i just recreate the body ?

**Comment by lo-th** [comment]
yes

**Comment by jeromeetienne** [comment]
thanks
