### ISSUE TITLE
Relative rotation in REV is busted (caused by bad matrix mult)

### ISSUE THREAD

**Issue by QuaziKb** [lo-th/Oimo.js#28]
There's a line in Sync-shapes which multiplies the shapes relative rotation 3x3 Matrix with the rigid body matrix, but the multiply order should be reversed, or else the relative rotation ends up creating a strange effect where objects with any relative rotation rotate inverted to the rigid body.

basically
 the line should be:
 shape.rotation.mul(this.rotation,shape.relativeRotation);
not the current:
 shape.rotation.mul(shape.relativeRotation,this.rotation);

**Comment by lo-th** [comment]
yes you right, correct in new version
