### ISSUE TITLE
setting body mass

### ISSUE THREAD

**Issue by mohamed--abdel-maksoud** [lo-th/Oimo.js#29]
Sorry in advance if my question is rather primitive, but I cannot see how to set the mass of an OIMO.Body. Background: I'm trying to use OIMO and one moving object keeps getting NaN position and rotation, I suspect it is because its mass is 0.

and before all: salute for the lean and fast engine!

**Comment by QuaziKb** [comment]
do you want to set it dynamically? you need to reference the rigidbody of the oimo.body and call setupmass() on it after you change the densities of all the contained shapes. it's kind of annoying right now but it's doable. look at the constructor for setupMass, and how the rigidbody is then initialized.

**Comment by lo-th** [comment]
you can set mass in config.density
but the mass is set automatically you have to add
move =  true for dynamique
or move = false for static
default is false

On Sat, Mar 14, 2015 at 7:46 AM, QuaziKb notifications@github.com wrote:

> do you want to set it dynamically? you need to reference the rigidbody of
> the oimo.body and call setupmass() on it after you change the densities of
> all the contained shapes. it's kind of annoying right now but it's doable.
> look at the constructor for setupMass, and how the rigidbody is then
> initialized.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/lo-th/Oimo.js/issues/29#issuecomment-80016602.

## 

LoTh - Freelance javascript / as3 / 3D
website http://perso.numericable.fr/chamaslot/ | blog
http://3dflashlo.wordpress.com

**Comment by mohamed--abdel-maksoud** [comment]
Thanks for the answers @QuaziKb and @lo-th !
I didn't set the config density in the initialization. I will set it and see if this helps.

**Comment by mohamed--abdel-maksoud** [comment]
OK, I managed to set the mass using the config parameter. It still didn't solve the original bug (I get NaN inverse inertia for some reason :/) but this is a different issue.

Thanks for your responses!
