### ISSUE TITLE
modularize, publish to npm

### ISSUE THREAD

**Issue by ghost** [lo-th/Oimo.js#3]
In the main example there are 17 script tags:
https://github.com/lo-th/Oimo.js/blob/master/index.html#L16-L32

That's not a great way for third parties to consume this library. It's common practice to generate a [umd](https://github.com/ForbesLindesay/umd) build so that people using module systems such as commonjs or AMD can `require()` this module and people not using any module system will still have their window globals as usual, but with only a single `<script>` tag to include.

Once the code has been modularized, you can generate a `package.json` file with [npm](https://npmjs.org), which ships by [node.js](http://nodejs.org) by default. Just do:

```
npm init
```

And the command will walk you through filling out the right fields. You should point the `"main"` field at the singular entry point for this package, which could be a dist build since the internals aren't modularized yet. A really simple way to do this with what you've already got is just to `cat` together all the files necessary and then append some `exports.FOO=...` statements, at least for commonjs. Once the build works, just publish to npm with:

```
npm publish
```

You can test the build with a tool like [browserify](http://browserify.org).

**Comment by lo-th** [comment]
hum i have to test that, i don't use command or node.js 
build folder is only containe final oimo.js version all other package is on js folder 
no need external download. But i have many update to do like compound rigidbody, shooting ball...

**Comment by positlabs** [comment]
IMO, it doesn't make sense to publish this library on npm. npm is for node packages, not client-side js libraries. If oimo.js is going to be published as a package, it should be on Bower. Bower is specifically used to manage front-end libraries like this one.

If I have time next week, I can try to take a stab at AMD modularization and publishing to Bower.

**Comment by computersarecool** [comment]
@positlabs I disagree with you here.  Babylon.js (which uses Oimo.js in its example documentation) is itself available at npm (as are many, many, many client side libaries).  I think @substack makes a great point - if this were available on npm, a person could just `npm install` babylon.js and oimo in a matter of seconds.  Please reconsider

**Comment by positlabs** [comment]
@computersarecool ditto. It's no longer true that npm is mainly server-side packages. If I could use it for server and client packages consistently, it would be ideal.

**Comment by computersarecool** [comment]
perhaps @lo-th might reconsider...

**Comment by sndrgb** [comment]
Any news about this?

**Comment by mwthink** [comment]
@lo-th should reconsider this for 2 reasons : 
1) Browserify. Being able to pull the package down through npm, list it as a project dependency (Just as with all my other depencendies)  would be an invaluable asset. As already stated, npm is certainly no longer just for server-side packages. 

2) Server-side running. This should also be coupled with a rewrite of some code that makes Oimo depend on canvas to operate. This would be Oimo an absolute knock-out of the park for a lot of projects. I am currently working on a multiplayer browser game, but with server side features, such as collision detection (And other anti-cheat measures). 

Obviously, my server has no need to be rendering graphics, but if I could run the same physics on the server that are running on the client, I wouldn't need to be resorting to a myriad of nasty hacks I've implemented in the mean time. 

I'm sure myself and some others who are interested could go about building the Oimo code to work in such a manner. Not a lot needs to be changed, but it would make all the difference in the world.

**Comment by nathanosdev** [comment]
I agree with making this an NPM package,
using NodeJS modules to build client side applications is becoming a lot more common.
It's a small effort to provide a package.json and publish to NPM.

**Comment by quasipedia** [comment]
Beginner in 3D here.
Using BabylonJS (as most of the people starting out).
Using webpack + babel (as most of the people doing webapps professionally).
Oimo seemed perfect for me.
Oimo has no npm package.
`yarn add cannon` instead.
Problem solved.
One user lost for Oimo, one user gained for Cannon.

**Comment by tiaod** [comment]
@quasipedia Awesome! I'm going to use cannonjs now! 😄

**Comment by lo-th** [comment]
yea npm version is on way
now i know how process 
like uil 

i hope someday Saharan help me for adding creazy function

**Comment by mwthink** [comment]
Great to hear about!
If there's any hiccups in the process, I'll see if there's anything I could contribute.

**Comment by lo-th** [comment]
is done !!!

**Comment by quasipedia** [comment]
🕺 🎆 🙇 ❤️
