### ISSUE TITLE
Is default scale 1 or 100?

### ISSUE THREAD

**Issue by amirebrahimi** [lo-th/Oimo.js#31]
The reason I ask is that Oimo.js has 100 as default scale, but the docs have 1. I can fix this and issue a pull request once I know what the default should be.

**Comment by lo-th** [comment]
scale is for three 
1 unit = 100 three unit

**Comment by amirebrahimi** [comment]
Ah, so I'm referring to this line:
https://github.com/lo-th/Oimo.js/blob/gh-pages/src/dev/Oimo.js#L14

I'm proposing that either this would be 1 here, or I can update the documentation for you to say that default is 100 to match with threejs usage and that one could use scale 1 for any other engine / integration.

**Comment by lo-th** [comment]
I have to update all  :( 
best is use 1 to avoid extra calculation 
now three can understand better little size

but for user set unit 10 is better than set 0.1 
so i have to think about that

**Comment by amirebrahimi** [comment]
No worries. That's the benefit of github as I can support you with suggestions. You don't have to do it all on your own :)

How about this? How about I set the scale to 1 by default and update all threejs demos to make sure they use an override of 100?

**Comment by lo-th** [comment]
Oimo use international system units from 0.1 to 10 meters max for dynamique body
for three i mutliply scale by 100 is more simple
