### ISSUE TITLE
Setting a new position on a static body?

### ISSUE THREAD

**Issue by that-ben** [lo-th/Oimo.js#33]
Hi, I've been scratching my head for a few hours trying various things and could not figure out why when I set a new position on a static (move:false) body, it wouldn't seem to take its place correctly.

I hacked through the OIMO source code and found a nifty little function that solved my issue, but it says in the comment there is no need to call from outside usually, so how is one supposed to set a new position on a static body without calling this and simulate for 1ms?

QUESTION #1 --> That's what I figured at the moment, am I doing it wrong? I'm doing this:

mybody.body.position.set(new_x, new_y, new_z);
mybody.body.updatePosition(1);

QUESTION #2 --> If I do that on many bodies, are the 1ms simulation happening on other bodies too? inb4 I test this myself thx :P

This is the function I found in the OIMO source code to make it work at the moment:

```
/** 
    * The time integration of the motion of a rigid body, you can update the information such as the shape. 
    * This method is invoked automatically when calling the step of the World, 
    * There is no need to call from outside usually. 
    * @param  timeStep time 
*/

updatePosition:function(timeStep){
    switch(this.type){
        case this.BODY_STATIC:
            this.linearVelocity.init();
            this.angularVelocity.init();
            // ONLY FOR TEST
            if(this.controlPos){
                this.position.copy(this.newPosition);
                this.controlPos = false;
            }
// --------------- ...ETC... --------------- 
```

**Comment by lo-th** [comment]
well if you want move object use dynamic {move:true} not static
to change position use bodys.setPosition({x:0, y:0, z:0});
that move object with the world scale

**Comment by Cobertos** [comment]
@lo-th 

What if I don't want my object to actually respond to collisions or move but I want to be able to reposition it. Is the above the accepted way of doing it?

**Comment by bondarenkovladislav** [comment]
Agree. Need an ability to move static bodies
