### ISSUE TITLE
Dynamic array resizing?

### ISSUE THREAD

**Issue by d07RiV** [lo-th/Oimo.js#34]
Why is there lots of code for doubling the size of arrays? Doesn't that serve absolutely no purpose with JS arrays being dynamic objects anyway?

I.e. https://github.com/lo-th/Oimo.js/blob/gh-pages/src/dev/collision/broadphase/BroadPhase.js #82

**Comment by lo-th** [comment]
yes not good practice for javascript, 
is a as3 artefact with vector 
can be a good way of optimisation if find best methode

**Comment by lo-th** [comment]
ok is mush better now
