### ISSUE TITLE
Collision Sounds?

### ISSUE THREAD

**Issue by pigloo** [lo-th/Oimo.js#39]
Hi @lo-th and other contributors thank you for sharing this great physics engine, it seems to be very fast!. I have been enjoying playing around with the examples and wondered if there is any way to easily add sounds on collision of objects in Three.js scenes?

**Comment by lo-th** [comment]
you can look here 
https://www.clicktorelease.com/code/io15/

**Comment by pigloo** [comment]
That should to the trick, I will have a dig. Thanks!
