### ISSUE TITLE
Rotation funky when using low negative numbers

### ISSUE THREAD

**Issue by pigloo** [lo-th/Oimo.js#40]
Hello

I have found some slightly odd behaviour with rotation of bodies, If you have a look at the link below you will see that when rotating the platform by -4 degrees the behaviour is as expected, but when rotating the platform by -3 to -1 degrees the platform rotates the opposite direction to what is expected.

http://www.pigloo.co.uk/oimo

```
var ground0 = world.add({size:[190, 40, 400], pos:[100,-20,0], rot:[-4,0,0], world:world});

// A look at 'ground0.rotation.elements' shows [1, -0, 0, 0, 0.9975640773773193, 0.06975647062063217, -0, -0.06975647062063217, 0.9975640773773193]

var ground1 = world.add({size:[190, 40, 400], pos:[-100,-20,0], rot:[-3,0,0], world:world});

// A look at 'ground1.rotation.elements' shows [1, 0, 0, 0, 0.9986295104026794, -0.0523359552025795, 0, 0.0523359552025795, 0.9986295104026794]
```

**Comment by pigloo** [comment]
I have created a pull request #41 for this issue

**Comment by lo-th** [comment]
fixed no more euler conversion 
http://lo-th.github.io/Oimo.js/index.html#rotation
