### ISSUE TITLE
Difference between .dev and .rev?

### ISSUE THREAD

**Issue by erichlof** [lo-th/Oimo.js#6]
Hi again,
What are the basic differences between .dev and .rev?  I noticed .rev had support for cylinder shapes where as .dev appears not to have the same support.  I'm confused because isn't .dev supposed to be the latest (with ALL the features that are not found in older versions)?

Oimo.js is looking better and better each day!  Keep up the great work!
Thanks,
-Erich

**Comment by lo-th** [comment]
Dev is the last yes but is not the same collision process.

the major differences are
DEV : 3 BroadPhases, 6 joints, 2 shapes, collision filter (in physics setting), accurate friction and restitution. code structure is more logical by avoiding redundancy.
REV : 2 BroadPhases, 4 joints, 3 shapes

saharan try another method for cylinder maybe in next release.

**Comment by erichlof** [comment]
Ok that clears up a lot.  Thanks! :)

**Comment by lo-th** [comment]
any way it is better to use DEV version
