### ISSUE TITLE
World properties

### ISSUE THREAD

**Issue by gregmax17** [lo-th/Oimo.js#62]
What do the different `broadphase`'s mean, what does brute, sweep & prune, and volume tree do?

What does `random` do, what does adding a random number in the simulation mean?

**Comment by lo-th** [comment]
Hi, is the algorithm used during collision detection

_brute is the most simple every object collid with other

_sweep & prune is more comlex and the best for many situation 
https://en.wikipedia.org/wiki/Sweep_and_prune

_volume tree is the most accurate but most complexe 
https://en.wikipedia.org/wiki/Bounding_volume_hierarchy

random change order of island array
so every simulation look different like real world
